# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSecimlerAl = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecimlerAl.setGeometry(QtCore.QRect(150, 300, 191, 61))
        self.btnSecimlerAl.setObjectName("btnSecimlerAl")
        self.groupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler.setGeometry(QtCore.QRect(130, 80, 241, 211))
        self.groupHobiler.setObjectName("groupHobiler")
        self.widget = QtWidgets.QWidget(self.groupHobiler)
        self.widget.setGeometry(QtCore.QRect(20, 20, 191, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbKitapOkumak = QtWidgets.QCheckBox(self.widget)
        self.cbKitapOkumak.setObjectName("cbKitapOkumak")
        self.verticalLayout.addWidget(self.cbKitapOkumak)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(500, 400, 191, 181))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.groupHobiler_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler_2.setGeometry(QtCore.QRect(490, 80, 241, 211))
        self.groupHobiler_2.setObjectName("groupHobiler_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupHobiler_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 191, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbBoksYapma = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbBoksYapma.setObjectName("cbBoksYapma")
        self.verticalLayout_2.addWidget(self.cbBoksYapma)
        self.cbYuzmek = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbYuzmek.setObjectName("cbYuzmek")
        self.verticalLayout_2.addWidget(self.cbYuzmek)
        self.cbFutbol = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbFutbol.setObjectName("cbFutbol")
        self.verticalLayout_2.addWidget(self.cbFutbol)
        self.btnSecimlerAl_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecimlerAl_2.setGeometry(QtCore.QRect(510, 300, 191, 61))
        self.btnSecimlerAl_2.setObjectName("btnSecimlerAl_2")
        self.lblResult_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblResult_2.setGeometry(QtCore.QRect(150, 390, 191, 181))
        self.lblResult_2.setText("")
        self.lblResult_2.setObjectName("lblResult_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSecimlerAl.setText(_translate("MainWindow", "Seçilenleri Al"))
        self.groupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbKitapOkumak.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.groupHobiler_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbBoksYapma.setText(_translate("MainWindow", "Boks Yapmak"))
        self.cbYuzmek.setText(_translate("MainWindow", "Yuzmek"))
        self.cbFutbol.setText(_translate("MainWindow", "Futbol oynamak"))
        self.btnSecimlerAl_2.setText(_translate("MainWindow", "Seçilenleri Al"))
